import json
import os
import base64
import requests
from dotenv import load_dotenv

# Load environment variables
load_dotenv()
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
print("GITHUB_TOKEN:", GITHUB_TOKEN)  # <-- add this here to check if token is loaded
REPO = "tooba393/AgenticAI_Assignment"

hf_key = os.environ.get("HF_API_KEY")
openai_key = os.environ.get("OPENAI_API_KEY")

# -------- LOAD SPEC --------
def load_spec():
    with open("product_specs.json", "r") as f:
        return json.load(f)

# -------- GENERATE HTML --------
def generate_html(spec):
    features = ""
    for f in spec["features"]:
        features += f"<div><h3>{f['name']}</h3><p>{f['description']}</p></div>"

    return f"""
    <html>
    <body>
        <h1>{spec['value_proposition']}</h1>
        <h2>Features</h2>
        {features}
        <button>Get Started</button>
    </body>
    </html>
    """

# -------- GITHUB HELPERS --------
def headers():
    return {"Authorization": f"token {GITHUB_TOKEN}"}

def create_issue():
    url = f"https://api.github.com/repos/{REPO}/issues"
    data = {
        "title": "Initial landing page",
        "body": "Auto-generated landing page"
    }
    r = requests.post(url, headers=headers(), json=data)
    if r.status_code != 201:
        print(f"Warning: Issue creation failed: {r.status_code} {r.text}")
        return None
    resp = r.json()
    return resp.get("html_url")  # safe access

def get_sha(branch="main"):
    url = f"https://api.github.com/repos/{REPO}/git/refs/heads/{branch}"
    r = requests.get(url, headers=headers())
    data = r.json()
    if "object" not in data:
        print("DEBUG get_sha response:", data)
        raise Exception(f"Cannot get SHA for branch '{branch}'. Check branch name and repo path.")
    return data["object"]["sha"]

def create_branch(branch):
    url = f"https://api.github.com/repos/{REPO}/git/refs"
    data = {"ref": f"refs/heads/{branch}", "sha": get_sha()}
    r = requests.post(url, headers=headers(), json=data)
    if r.status_code not in [200, 201]:
        print(f"Warning: Branch creation failed: {r.status_code} {r.text}")

def commit_file(branch, content):
    url = f"https://api.github.com/repos/{REPO}/contents/index.html"
    encoded = base64.b64encode(content.encode()).decode()
    data = {
        "message": "Landing page",
        "content": encoded,
        "branch": branch
    }
    r = requests.put(url, headers=headers(), json=data)
    if r.status_code not in [200, 201]:
        print(f"Warning: File commit failed: {r.status_code} {r.text}")

def create_pr(branch):
    url = f"https://api.github.com/repos/{REPO}/pulls"
    data = {
        "title": "Landing Page PR",
        "head": branch,
        "base": "main",
        "body": "Generated by Engineer Agent"
    }
    r = requests.post(url, headers=headers(), json=data)
    if r.status_code != 201:
        print(f"Warning: PR creation failed: {r.status_code} {r.text}")
        return None
    resp = r.json()
    return resp.get("html_url")  # safe access

# -------- MAIN --------
def run_engineer():
    spec = load_spec()
    html = generate_html(spec)

    issue = create_issue()
    branch = "landing-page-branch"
    create_branch(branch)
    commit_file(branch, html)
    pr = create_pr(branch)

    print("✅ DONE")
    print({
        "issue": issue or "Issue creation failed",
        "pr": pr or "PR creation failed"
    })


if __name__ == "__main__":
    run_engineer()